import http from 'node:http'
import os from 'node:os'
import { execFile } from 'node:child_process'
import isPortReachable from 'is-port-reachable'
import { detectLanIps } from './bootstrap.js'
import { detectFirewall, firewallCommands, type FirewallInfo, type FirewallPlatform } from './firewall.js'
import type { ConfigStore, NetworkSettings } from './config-store.js'
import { logger } from './logger.js'
import { isRemoteAccessEnabled } from './network-access.js'
import { computeWslPortForwardingPlanAsync } from './wsl-port-forward.js'

const log = logger.child({ component: 'network-manager' })
const WINDOWS_FIREWALL_QUERY_TIMEOUT_MS = 10_000

type ExecFileSettledResult = {
  error: Error | null
  stdout: string
  stderr: string
}

function toExecText(value: unknown): string {
  if (typeof value === 'string') {
    return value
  }

  if (value instanceof Uint8Array) {
    return Buffer.from(value).toString('utf-8')
  }

  return ''
}

function execFileSettledAsync(
  command: string,
  args: string[],
  options: { encoding: 'utf-8'; timeout: number },
): Promise<ExecFileSettledResult> {
  return new Promise((resolve) => {
    execFile(command, args, options, (error, stdout, stderr) => {
      resolve({
        error: error ?? null,
        stdout: toExecText(stdout),
        stderr: toExecText(stderr),
      })
    })
  })
}

function getManagedWindowsFirewallRuleName(port: number): string {
  return `Freshell (port ${port})`
}

async function getExistingManagedWindowsFirewallPorts(ports: number[]): Promise<Set<number>> {
  const existingPorts = new Set<number>()

  await Promise.all(ports.map(async (port) => {
    const ruleName = getManagedWindowsFirewallRuleName(port)
    const { error, stdout, stderr } = await execFileSettledAsync(
      'netsh',
      ['advfirewall', 'firewall', 'show', 'rule', `name=${ruleName}`],
      { encoding: 'utf-8', timeout: WINDOWS_FIREWALL_QUERY_TIMEOUT_MS },
    )

    const output = `${stdout}\n${stderr}`
    if (!error || output.includes(ruleName)) {
      existingPorts.add(port)
    }
  }))

  return existingPorts
}

function buildWindowsFirewallAddCommands(ports: number[]): string[] {
  return ports.map(
    (port) => `netsh advfirewall firewall add rule name="${getManagedWindowsFirewallRuleName(port)}" dir=in action=allow protocol=TCP localport=${port} profile=private`,
  )
}

function buildWindowsFirewallRepairCommands(
  requiredPorts: number[],
  existingManagedPorts: Set<number>,
  advertisedPortReachable: boolean,
): string[] {
  const requiredPortSet = new Set(requiredPorts)
  const stalePorts = Array.from(existingManagedPorts)
    .filter((port) => !requiredPortSet.has(port))
    .sort((a, b) => a - b)
  const addPorts = advertisedPortReachable
    ? requiredPorts.filter((port) => !existingManagedPorts.has(port))
    : requiredPorts

  return [
    ...stalePorts.map(
      (port) => `netsh advfirewall firewall delete rule name="${getManagedWindowsFirewallRuleName(port)}" 2>$null`,
    ),
    ...buildWindowsFirewallAddCommands(addPorts),
  ]
}

export interface NetworkStatus {
  configured: boolean
  host: '127.0.0.1' | '0.0.0.0'
  remoteAccessEnabled: boolean
  remoteAccessRequested: boolean
  remoteAccessNeedsRepair: boolean
  port: number
  lanIps: string[]
  machineHostname: string
  firewall: {
    platform: FirewallPlatform
    active: boolean
    portOpen: boolean | null
    commands: string[]
    configuring: boolean
  }
  rebinding: boolean
  devMode: boolean
  devPort?: number
  accessUrl: string
}

export class NetworkManager {
  private firewallInfo: FirewallInfo | null = null
  private lanIps: string[] = []
  private lanIpsInitialized = false
  private wsHandler: {
    prepareForRebind(): void
    resumeAfterRebind(): void
    broadcast(msg: unknown): void
  } | null = null
  private rebindInFlight = false
  private pendingRebindConfig: NetworkSettings | null = null
  private firewallConfiguring = false
  private userAllowedOrigins: string[]

  constructor(
    private server: http.Server,
    private configStore: ConfigStore,
    private port: number,
    private devMode: boolean = false,
    private devPort?: number,
  ) {
    // Parse user-specified extra origins from EXTRA_ALLOWED_ORIGINS env var
    const extraEnv = process.env.EXTRA_ALLOWED_ORIGINS ?? ''
    const extraOrigins = extraEnv.split(',').map(o => o.trim()).filter(Boolean)

    if (extraOrigins.length === 0 && process.env.ALLOWED_ORIGINS) {
      // Migration: check for non-auto-generated entries in ALLOWED_ORIGINS.
      // Must populate lanIps first so auto-generated LAN entries are recognized.
      this.ensureLanIps()
      const knownPorts = [this.port]
      if (this.devMode && this.devPort) knownPorts.push(this.devPort)
      const knownHosts = ['localhost', '127.0.0.1', ...this.lanIps]
      const autoGeneratedOrigins = new Set(
        knownHosts.flatMap(host =>
          knownPorts.map(p => `http://${host}:${p}`)
        )
      )
      const legacyCustom = process.env.ALLOWED_ORIGINS
        .split(',').map(o => o.trim()).filter(Boolean)
        .filter(origin => !autoGeneratedOrigins.has(origin))
      if (legacyCustom.length > 0) {
        log.warn(
          { origins: legacyCustom },
          'ALLOWED_ORIGINS contains custom entries. These will be preserved but ' +
          'please move them to EXTRA_ALLOWED_ORIGINS (ALLOWED_ORIGINS is now auto-managed).',
        )
        this.userAllowedOrigins = legacyCustom
      } else {
        this.userAllowedOrigins = extraOrigins
      }
    } else {
      this.userAllowedOrigins = extraOrigins
    }
  }

  setWsHandler(handler: {
    prepareForRebind(): void
    resumeAfterRebind(): void
    broadcast(msg: unknown): void
  }): void {
    this.wsHandler = handler
  }

  private async getFirewallInfo(): Promise<FirewallInfo> {
    if (!this.firewallInfo) {
      this.firewallInfo = await detectFirewall()
    }

    return this.firewallInfo
  }

  async getStatus(): Promise<NetworkStatus> {
    const settings = await this.configStore.getSettings()
    const network = settings.network

    this.ensureLanIps()
    const firewallInfo = await this.getFirewallInfo()

    const remoteAccessPorts = this.getRemoteAccessPorts()

    // Use the actual server bind address, not the config value. On WSL2
    // the server binds to 0.0.0.0 regardless of config (for Windows host
    // access), so the config value may not reflect the real bind state.
    const addr = this.server.address()
    const actualHost = (addr && typeof addr === 'object') ? addr.address : null
    const effectiveHost: '127.0.0.1' | '0.0.0.0' =
      actualHost === '0.0.0.0' || actualHost === '::' ? '0.0.0.0'
      : actualHost === '127.0.0.1' || actualHost === '::1' ? '127.0.0.1'
      // Server not yet listening — fall back to config-based logic
      : (!network.configured && (process.env.HOST === '0.0.0.0' || process.env.HOST === '127.0.0.1'))
        ? process.env.HOST as '127.0.0.1' | '0.0.0.0'
        : network.host

    let rawPortOpen: boolean | null = null
    if (effectiveHost === '0.0.0.0' && this.lanIps.length > 0) {
      const probeResults = await Promise.all(
        remoteAccessPorts.map(async (port) => {
          try {
            return await isPortReachable(port, { host: this.lanIps[0], timeout: 2000 })
          } catch {
            return null
          }
        }),
      )

      if (probeResults.includes(false)) {
        rawPortOpen = false
      } else if (probeResults.includes(null)) {
        rawPortOpen = null
      } else {
        rawPortOpen = true
      }
    }

    const remoteAccessRequested = isRemoteAccessEnabled(network, effectiveHost, firewallInfo.platform)
    const legacyDevUpgradePorts = this.devMode
      ? this.getRelevantPorts().filter((port) => !remoteAccessPorts.includes(port))
      : []
    let staleUpgradeExposure = false
    let existingManagedWindowsPorts = new Set<number>()

    if (
      remoteAccessRequested
      && effectiveHost === '0.0.0.0'
      && legacyDevUpgradePorts.length > 0
    ) {
      if (firewallInfo.platform === 'wsl2') {
        const wslPlan = await computeWslPortForwardingPlanAsync(remoteAccessPorts, this.getRelevantPorts())
        staleUpgradeExposure = wslPlan.status === 'ready'
      } else if (firewallInfo.platform === 'windows' && firewallInfo.active) {
        existingManagedWindowsPorts = await getExistingManagedWindowsFirewallPorts(this.getRelevantPorts())
        staleUpgradeExposure = Array.from(existingManagedWindowsPorts)
          .some((port) => !remoteAccessPorts.includes(port))
      }
    }

    const portOpen = staleUpgradeExposure ? false : rawPortOpen
    const commands = firewallInfo.active
      ? firewallInfo.platform === 'windows' && staleUpgradeExposure
        ? buildWindowsFirewallRepairCommands(remoteAccessPorts, existingManagedWindowsPorts, rawPortOpen === true)
        : firewallCommands(firewallInfo.platform, remoteAccessPorts)
      : []
    const remoteAccessEnabled = firewallInfo.platform === 'wsl2'
      ? rawPortOpen === true
      : remoteAccessRequested && rawPortOpen === true
    const remoteAccessNeedsRepair = (
      firewallInfo.platform === 'wsl2'
      && remoteAccessRequested
      && portOpen === false
    ) || (
      firewallInfo.platform === 'windows'
      && remoteAccessRequested
      && (rawPortOpen === false || staleUpgradeExposure)
    )
    const shareRouteEnabled = remoteAccessEnabled
      || (
        firewallInfo.platform === 'wsl2'
        && remoteAccessRequested
        && rawPortOpen === null
      )

    const token = process.env.AUTH_TOKEN ?? ''
    const accessHost = shareRouteEnabled
      ? (this.lanIps[0] ?? 'localhost')
      : 'localhost'
    const accessPort = this.devMode && this.devPort ? this.devPort : this.port
    const accessUrl = `http://${accessHost}:${accessPort}/?token=${encodeURIComponent(token)}`

    return {
      configured: network.configured,
      host: effectiveHost,
      remoteAccessEnabled,
      remoteAccessRequested,
      remoteAccessNeedsRepair,
      port: this.port,
      lanIps: this.lanIps,
      machineHostname: os.hostname().replace(/\.local$/, ''),
      firewall: {
        platform: firewallInfo.platform,
        active: firewallInfo.active,
        portOpen,
        commands,
        configuring: this.firewallConfiguring,
      },
      rebinding: this.rebindInFlight,
      devMode: this.devMode,
      devPort: this.devPort,
      accessUrl,
    }
  }

  async configure(network: NetworkSettings): Promise<{ rebindScheduled: boolean }> {
    const firewallInfo = await this.getFirewallInfo()

    // Use the actual server bind address to detect host changes. On WSL2
    // the server starts on 0.0.0.0 regardless of config, so comparing
    // against the config value would cause spurious rebinds.
    const addr = this.server.address()
    const actualHost = (addr && typeof addr === 'object') ? addr.address : null
    const effectiveCurrentHost =
      actualHost === '0.0.0.0' || actualHost === '::' ? '0.0.0.0'
      : actualHost === '127.0.0.1' || actualHost === '::1' ? '127.0.0.1'
      : null
    // On WSL, the listener stays on 0.0.0.0 and the saved host is only an intent flag.
    const hostChanged = firewallInfo.platform !== 'wsl2'
      && effectiveCurrentHost !== null
      && effectiveCurrentHost !== network.host

    await this.configStore.patchSettings({ network })

    this.firewallInfo = null
    this.refreshLanIps()
    await this.rebuildAllowedOrigins()

    if (hostChanged && this.server.listening) {
      if (this.rebindInFlight) {
        log.warn({ host: network.host }, 'Rebind in flight, queuing configure')
        this.pendingRebindConfig = network
        return { rebindScheduled: true }
      }
      this.rebindInFlight = true
      setImmediate(() => {
        this.rebind(network.host).catch((err) => {
          log.error({ err }, 'Hot rebind failed')
        })
      })
      return { rebindScheduled: true }
    }

    return { rebindScheduled: false }
  }

  async initializeFromStartup(
    _effectiveHost: '127.0.0.1' | '0.0.0.0',
    _network: NetworkSettings,
  ): Promise<void> {
    this.refreshLanIps()
    await this.rebuildAllowedOrigins()
  }

  private async rebind(host: string): Promise<void> {
    if (!this.rebindInFlight) {
      log.error({ host }, 'rebind() called without rebindInFlight set')
      this.rebindInFlight = true
    }

    const addr = this.server.address()
    const oldHost = (addr && typeof addr === 'object') ? addr.address : '127.0.0.1'

    log.info({ host, port: this.port, oldHost }, 'Hot rebinding server')

    if (this.wsHandler) {
      log.info('Preparing WsHandler for rebind')
      this.wsHandler.prepareForRebind()
    }

    try {
      await new Promise<void>((resolve, reject) => {
        this.server.close((err) => {
          if (err) {
            log.error({ err }, 'Failed to close server for rebind')
            reject(err)
            return
          }

          const onListenError = (listenErr: Error) => {
            log.error({ err: listenErr, host }, 'Failed to rebind server to new host')

            const onRollbackError = (rollbackErr: Error) => {
              log.error(
                { err: rollbackErr, originalErr: listenErr, oldHost, port: this.port },
                'CATASTROPHIC: Rollback bind also failed — server has no active listener',
              )
              reject(listenErr)
            }
            this.server.once('error', onRollbackError)
            this.server.listen(this.port, oldHost, async () => {
              this.server.removeListener('error', onRollbackError)
              log.warn({ oldHost, port: this.port }, 'Rolled back to previous bind address')

              try {
                await this.configStore.patchSettings({
                  network: { host: oldHost as '127.0.0.1' | '0.0.0.0' },
                } as any)
                await this.rebuildAllowedOrigins()
                if (this.wsHandler) {
                  const correctedSettings = await this.configStore.getSettings()
                  this.wsHandler.broadcast({
                    type: 'settings.updated',
                    settings: correctedSettings,
                  })
                }
              } catch (patchErr) {
                log.error({ err: patchErr }, 'Failed to revert config/origins after rebind failure')
              }
              reject(listenErr)
            })
          }
          this.server.once('error', onListenError)

          this.server.listen(this.port, host, () => {
            this.server.removeListener('error', onListenError)
            log.info({ host, port: this.port }, 'Server rebound successfully')
            resolve()
          })
        })
      })
    } finally {
      if (this.wsHandler) {
        this.wsHandler.resumeAfterRebind()
        log.info('WsHandler resumed after rebind')
      }
      this.rebindInFlight = false

      const queuedConfig = this.pendingRebindConfig
      this.pendingRebindConfig = null
      if (queuedConfig !== null) {
        log.info({ host: queuedConfig.host }, 'Processing queued configure')
        setImmediate(() => {
          this.configure(queuedConfig).catch((err) => {
            log.error({ err }, 'Queued configure failed')
          })
        })
      }
    }
  }

  resetFirewallCache(): void {
    this.firewallInfo = null
  }

  setFirewallConfiguring(configuring: boolean): void {
    this.firewallConfiguring = configuring
  }

  getRelevantPorts(): number[] {
    const ports = [this.port]
    if (this.devMode && this.devPort && this.devPort !== this.port) {
      ports.push(this.devPort)
    }
    return ports
  }

  getRemoteAccessPorts(): number[] {
    if (this.devMode && this.devPort) {
      return [this.devPort]
    }
    return [this.port]
  }

  private ensureLanIps(): void {
    if (!this.lanIpsInitialized) {
      this.refreshLanIps()
      this.lanIpsInitialized = true
    }
  }

  private refreshLanIps(): void {
    try {
      this.lanIps = detectLanIps()
    } catch {
      this.lanIps = []
    }
  }

  private buildAllowedOrigins(network: NetworkSettings): string[] {
    const userOrigins = this.userAllowedOrigins ?? []

    // Use the EFFECTIVE host (accounting for HOST env override when unconfigured),
    // not just the config host. This prevents a mismatch where the server binds to
    // 0.0.0.0 (via HOST env) but origins only include localhost.
    const effectiveHost = (!network.configured && (process.env.HOST === '0.0.0.0' || process.env.HOST === '127.0.0.1'))
      ? process.env.HOST
      : network.host

    // Always include loopback origins with explicit ports (both localhost and 127.0.0.1).
    const origins = [
      ...userOrigins,
      `http://localhost:${this.port}`,
      `http://127.0.0.1:${this.port}`,
    ]
    if (this.devPort) {
      origins.push(`http://localhost:${this.devPort}`)
      origins.push(`http://127.0.0.1:${this.devPort}`)
    }
    if (effectiveHost === '0.0.0.0' && this.lanIps.length > 0) {
      for (const ip of this.lanIps) {
        origins.push(`http://${ip}:${this.port}`)
        if (this.devPort) origins.push(`http://${ip}:${this.devPort}`)
      }
    }
    return [...new Set(origins)]
  }

  async rebuildAllowedOrigins(): Promise<void> {
    try {
      const settings = await this.configStore.getSettings()
      const origins = this.buildAllowedOrigins(settings.network)
      process.env.ALLOWED_ORIGINS = origins.join(',')
    } catch (err) {
      log.error({ err }, 'Failed to rebuild ALLOWED_ORIGINS')
    }
  }

  async stop(): Promise<void> {
    // No-op; retained for interface compatibility
  }
}
